# Path oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

#export ZSH_THEME="bira"
export ZSH_THEME="eastwood"

plugins=(cap vi-mode brew github git gem rails rails3 osx vagrant)

source $ZSH/oh-my-zsh.sh

export PATH="~/bin:/usr/local/Cellar/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/git/bin::$PATH"

# Set macvim as the default editor
export EDITOR='mate -w'

# Load RVM
unsetopt auto_name_dirs
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

alias pautotest="autotest -p"
alias migrate="rake db:migrate db:test:clone"
alias pmigrate="rake db:migrate parallel:prepare"
alias rst="touch tmp/restart.txt"
